In [45]:
import numpy as np

In [49]:
ar=np.arange(1,10)
print(ar)
print(ar[1:5])


[1 2 3 4 5 6 7 8 9]
[2 3 4 5]


In [107]:
da=ar.reshape(3,3)
print('da>>\n',da)

da>>
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [114]:
print(da[0:1],'< 0-1>')
print(da[1:],'<1--><>// ')
print(da[2:] ,' < 2-->')

[[1 2 3]] < 0-1>
[[4 5 6]
 [7 8 9]] <1--><>// 
[[7 8 9]]  < 2-->


In [129]:
print(da[0:,1:2])   ###( <specify the range in a row>, <specify range of..rows > )
##   (0:,1:3) means from 0 to last elem, and from 1 to 2 row...


[[2]
 [5]
 [8]]
