In [1]:
import numpy as np
import pandas as pd

In [35]:
xx=np.zeros(11)
print(xx)
print(xx+1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [38]:
xx+5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [1]:
np.random.randint(1,100)

NameError: name 'np' is not defined

In [1]:
print('xxx')



xxx
